export const testObj = {
	success: true,
	order: {
		orderId: 'order-f6760',
		user: 'guest',
		status: 'pending',
		items: [
			{
				id: 'meal124',
				quantity: 2,
				extras: [],
				without: [],
				name: 'Testmojj',
				subtotal: 75,
			},
			{
				id: 'meal124',
				quantity: 1,
				extras: [],
				without: [],
				name: 'Vålberg vego',
				subtotal: 45,
			},
		],
		total: 45,
		userComment: 'Körv körv körv!!!',
		staffComment: 'Klara gillar kategorier',
		createdAt: '2025-11-19T11:59:15.647Z',
		modifiedAt: '2025-11-19T11:59:15.647Z',
	},
};

export const testMeals = [
	{
		id: 'meal-0b691',
		name: 'Grillad med mos',
		category: 'MEAL',
		price: 88,
		summary: 'En grillad kôrv med mos',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-19T04:30:07.575Z',
		items: ['prod-dcd81', 'prod-41448'],
		status: 'active',
	},
	{
		id: 'meal-1ef03',
		name: 'Halv special',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:18:17.100Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-2417b',
		name: 'Kôrv mä mos',
		category: 'MEAL',
		price: 35,
		summary: 'En kokt korv med mos. Simple as that.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: 'prod-c3536',
		createdAt: '2025-11-18T13:54:56.215Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-2c7f5',
		name: 'Metalmojjen',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:17:57.452Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-34bb0',
		name: 'Mosbricka',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:19:23.357Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-38923',
		name: 'Pokekôrv',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:19:06.519Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-68f7b',
		name: 'Härta härta',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:18:41.728Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-7b6f5',
		name: 'Favoriten',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:19:38.127Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-b54dc',
		name: 'Deje dubbel',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:18:09.746Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
	{
		id: 'meal-c86cb',
		name: 'Hel special',
		category: 'MEAL',
		price: 55,
		summary: 'En kort beskrivning av produkten.',
		details: '',
		img: 'www.enbraurl.se',
		includeDrink: null,
		createdAt: '2025-11-20T12:18:22.684Z',
		items: ['prod-30ec8', 'prod-a1737'],
		status: 'active',
	},
];
